# -*- coding: utf-8 -*-
"""Tratar Variaveis Categoricas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdId7622OMU2Gdcx7ODMKOZmSQ5Suzea
"""

#import libraries 
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

url='https://github.com/Diegojfsr/RNA_Trabalho_Pratico_I/blob/main/test.csv?raw=true'
test = pd.read_csv(url)
url='https://github.com/Diegojfsr/RNA_Trabalho_Pratico_I/blob/main/train.csv?raw=true'
train = pd.read_csv(url)

train.head()

train.info(verbose=True)

train_categ = train.select_dtypes(include='object') # A variavel train_categ recebe os dados categoricos
train_categ.describe()

train.select_dtypes(include='object').describe()

#OneHotEncoding

!pip install category_encoders

import category_encoders as ce

from category_encoders.one_hot import OneHotEncoder, OrdinalEncoder

train['HomePlanet'] # Exibe a coluna HomePlanet(Selecionei essa coluna para converter valores)

OneHotEnc = OneHotEncoder(cols=['HomePlanet']) # A variavel OneHotEnc recebe os dados convertidos de HomePlanet // Converte a coluna HomePlanet

OH = OneHotEnc.fit_transform(train_categ) # OH recebe a junção das colunas convertidas (OneHotEnc) com as demais do Dataframe

OH.info(verbose=True)

OH.head()

#OrdinalEncoding

train.columns

OderEnc = OrdinalEncoder(cols =['Destination'])  # A variavel OrderEnc recebe os dados convertidos de Destination // Converte a coluna Destination

OE = OderEnc.fit_transform(train_categ) # Faz a junção da coluna convertida com as demais do Dataframe //mas descarta a conversao anterior

OE.head()

OderEnc.fit_transform(OH)  # Junta a conversao de OrderEnc + os dados da Variavel OH

OE = OderEnc

OE